Repository Braspag/woocommerce, pull requests merged in 2025-02, with the labels that each got.

#17 Fix: add static in method class API query
  includes/class-wc-braspag-pagador-api-query.php
Labels: bug

#19 Feature/add extradatacollection
  includes/payment-methods/class-wc-gateway-braspag-boleto.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard-justclick.php
  includes/payment-methods/class-wc-gateway-braspag-creditcard.php
  includes/payment-methods/class-wc-gateway-braspag-debitcard.php
Labels: enhancement

#20 Docs version chancelog
  changelog.txt
  readme.txt
  wc-gateway-braspag.php
Labels: documentation
